---
title: "Statistics"
autor: Mariam Hovhannisyan
---


```{r}
#1 Treatment effects are best estimated using data from (a) randomized, controlled experiments.
#2 Randomized, controlled experiments are needed to accurately measure treatment effects without (d) selection bias

```

```{r}
#3 in 7 months in a 100-unit motely 14 rooms were taken out of service for one month at a time
library(readxl)
library(dplyr)
library(ggplot2)
library(ggpubr)
```


```{r}
#a
data <- read_excel('motel.xlsx')
head(data)
data
```

```{r}

occupation<-ggplot(data, aes(time)) + 
  geom_line(aes(y = comp_pct, color = 'green'))+
  geom_line(aes(y = motel_pct, color = 'blue')) + 
  scale_color_manual(labels = c("comp_pct", "motel_pct"), values = c("green", "blue"))  + 
  xlab('month') + ylab('occ rate') 
print(occupation)

#The rapair took place from the 17th to 23th month, the graph obviously shows that the occupation rate of the motel is much less than that of the competitors, however there are similar patterns during th erepair period
```

```{r}

motel0 <- mean(data[data$repair == 0, ]$motel_pct)
comp0 <- mean(data[data$repair == 0, ]$comp_pct)

motel1 <- mean(data[data$repair == 1, ]$motel_pct)
comp1 <- mean(data[data$repair == 1, ]$comp_pct)


diff <- motel0 - comp0
print(diff)
# The difference between averages occupancy rate during non-repair period is 16.86
```
```{r}
MStar = comp1 + diff
estim = MStar - motel1
print(estim)

#estimate of lost occupancy is 14.118
```
```{r}
 #Compute the amount of revenue lost during the seven-month period (215 days) assuming an average room rate of $56.61 per night
lost_rev = 14*56.61*31 #14rooms were taken down for one time month each
lost_rev
```

```{r}
#) Draw a revised version of Figure 7.3 (POR), that explains the calculations in part
d1 <- data.frame("x" = c(0, 20), 'y' = c(comp0, comp1))
d2 <- data.frame("x" = c(0, 20), 'y' = c(motel0, MStar ))
d3 <- data.frame("x" = c(0, 20), 'y' = c(motel0, motel1))


ggplot() + geom_line(d1, aes(x, y)) + geom_line(d2, aes(x, y)) + geom_line(d3, aes(x, y)) +
  annotate("text", x=0, y=30, label= "Before") + 
  annotate("text", x = 20, y=30, label = "After")
  
```
```{r}
model <- lm(motel_pct ~ comp_pct + relprice + repair, data = data)
summary(model)

#s. Interpret the estimated coefficients, as well as their signs and significance
#b0 is 120.7561, meaning regardless the factors the motel pct will be positive.  0.6326 is the estimate intercept for competitor percentage, meaning in case of each unit increase in it own motel percentage will also increase. Aliigned with th economic logic, the intercept for relative price is negative ( -106.9659), meaning each unit increase in the market price will bring negative effect on the motel occupancy. However, lets note that this factor has comparably low significance on th emodel. And the indicator variable of repair period also has a negative correlation affect on the motel occupancy (-18.1441) being the most significant factor in this model.  


```

```{r}
#compute an estimate of the revenue lost by the damaged motel during the repair period (215 days @ $56.61 Ã—ð›½4)
rep_loss = 18.1441*215*56.11
print(rep_loss)
print(lost_rev)
lost_rev-rep_loss
#the estimate lost revenue was less than the loss considering the repair period estimate
```

```








