---
title: "TTest"
author: "Mariam Hovhannisyan"
date: "12/9/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(BayesFactor)
library(ggplot2)
library(cowplot)

data <- read_excel("concrete.xlsx")
```
```{r}
seven <- hist(concrete$Strenght[concrete$Days==1])
two <- hist(concrete$Strenght[concrete$Days==0])
plot_grid(two, seven, align = 'v', nrow = 2)

#H0: mean2 is related to mean7
#H1: mean2 is not related to mean7
```

```{r}
t.test(x = concrete$Strenght[concrete$Days==0], y = concrete$Strenght[concrete$Days==1], paired=TRUE)
p> alpha => fail to reject H0 => not enough evidence to claim that mean2 is not related to mean 7

```
```{r}
#H0: mean2 is related to mean7
#H1: mean2 is not related to mean7

ttestBF(x = concrete$Strenght[concrete$Days==0], y = concrete$Strenght[concrete$Days==1], paired=TRUE)
```
p<1 => fail to reject H0, not enough evidence to claim that mean2 is not related to mean7 
Both tests show the same results, however I'd prefer using t.test in these cases, as I noticed that it gave the result in less time than the BF



